boiska/urls.py
from django.conf.urls import url
from . import views

app_name = 'boiska'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(),
        name='index'
    ),
    url(r'^(?P<place_name>[\w ]+)$',
        views.PlaceView.as_view(),
        name='place'
    ),
    url(r'^(?P<place_name>[\w ]+)/'
        r'(?P<year>\d{4})/'
        r'(?P<month>\d\d?)$',
        views.PlaceView.as_view(),
        name='place'
    ),
    url(r'(?P<place_name>[\w ]+)/'
        r'(?P<year>\d{4})/'
        r'(?P<month>\d\d?)/'
        r'(?P<day>\d\d?)$',
        views.PlaceDayView.as_view(),
        name='place_day'
    ),
    url(r'(?P<place_name>[\w ]+)/'
        r'admin$',
        views.PlaceAdminView.as_view(),
        name='place_admin'
    ),
    url(r'(?P<place_name>[\w ]+)/'
        r'admin/edit_reservation/'
        r'(?P<reservation_id>\d+)$',
        views.EditReservationView.as_view(),
        name='edit_reservation'
    ),
    url(r'(?P<place_name>[\w ]+)/'
        r'admin/edit_place$',
        views.EditPlaceView.as_view(),
        name='edit_place'
    ),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('boiska.urls')),
]

boiska/models.py
from django.contrib.auth.models import User
from django.db import models
from django.core.validators import RegexValidator


class Place(models.Model):
    """
    Place is a location with sports grounds. Administrator is a person
    who can edit info about a Place and manage registrations.
    """
    name = models.CharField(
        max_length=40,
        primary_key=True,
        validators=[
            RegexValidator(
                regex='[\w ]+',
                message='Name may contain only letters, numbers, underscores and spaces.'
            )
        ]
    )
    administrator = models.ForeignKey(
        User,
        on_delete=models.CASCADE
    )
    description = models.CharField(max_length=500)
    phone_number = models.CharField(max_length=20, default=None)
    city = models.CharField(max_length=30)
    street = models.CharField(max_length=50)
    def __str__(self):
        return self.name


class SportsGround(models.Model):
    """
    SportsGround is a pitch/court which belongs to a Place and can have
    reservations attached to it.
    SportsGround can be closed for some time, for example during
    the winter.
    """
    place = models.ForeignKey(
        Place,
        on_delete=models.CASCADE,
        related_name='sports_grounds'
    )
    name_prefix = models.CharField(
        max_length=30,
        default='Boisko nr',
        blank=True
    )
    local_id = models.PositiveIntegerField(blank=True, default=None)
    opening_time = models.TimeField()
    closing_time = models.TimeField()
    start_season_date = models.DateField(
        blank=True,
        null=True,
        default=None
    )
    end_season_date = models.DateField(
        blank=True,
        null=True,
        default=None
    )
    
    class Meta:
        unique_together = ('place', 'name_prefix', 'local_id')
        ordering = ['name_prefix', 'local_id']
    
    def local_name(self):
        return self.name_prefix + ' ' + str(self.local_id)
    
    def get_local_id(self):
        """
        This function is used when a SportsGround instance is being saved.
        """
        sports_grounds = self.place.sports_grounds.filter(
            name_prefix=self.name_prefix
        ).order_by('-local_id')
        present_id = sports_grounds.values_list('local_id', flat=True)
        if present_id:
            return present_id[0] + 1
        else:
            return 1
    
    def save(self, *args, **kwargs):
        if self.local_id is None:
            self.local_id = self.get_local_id()
        super(SportsGround, self).save(*args, **kwargs)
    
    def __str__(self):
        result = self.name_prefix + ' '
        result += str(self.local_id) + ', ' + self.place.name
        return result


class Reservation(models.Model):
    """
    Reservation of a specific SportsGround.
    Email, surname, start_time, end_time are required.
    Event_date and is_accepted fields are set automatically.
    """
    sports_ground = models.ForeignKey(
        SportsGround,
        on_delete=models.CASCADE,
        related_name='reservations'
    )
    email = models.EmailField()
    surname = models.CharField(max_length=40)
    event_date = models.DateField()
    start_time = models.TimeField()
    end_time = models.TimeField()
    is_accepted = models.BooleanField(blank=True, default=False)
    
    ACCEPT = 1
    DELETE = 2
    ACTION_CHOICES = (
        (ACCEPT, 'Accept selected reservations'),
        (DELETE, 'Delete selected reservations'),
    )
    
    def __str__(self):
        event_time = (self.start_time.strftime('%H:%M')
            + ' - ' + self.end_time.strftime('%H:%M'))
        when = str(self.event_date) + ', ' + event_time
        return str(self.sports_ground) + ', ' + when

boiska/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import Place, Reservation, SportsGround

class ReservationForm(forms.ModelForm):
    def __init__(self, place=None, *args, **kwargs):
        """
        Limit sports grounds to these that belong to the particular place.
        """
        super(ReservationForm, self).__init__(*args, **kwargs)
        if place is not None:
            self.fields['sports_ground'].queryset = SportsGround.objects.filter(place=place)
    
    def clean(self):
        super(ReservationForm, self).clean()
        start_time = self.cleaned_data.get('start_time')
        end_time = self.cleaned_data.get('end_time')
        if start_time and end_time:
            sports_ground = self.cleaned_data['sports_ground']
            opening_time = sports_ground.opening_time
            closing_time = sports_ground.closing_time
            if start_time >= end_time or start_time < opening_time or end_time > closing_time:
                raise ValidationError('Nieprawidłowe godziny trwania rezerwacji.')
        return self.cleaned_data


class NewReservationForm(ReservationForm):
    class Meta:
        model = Reservation
        fields = ('sports_ground', 'start_time', 'end_time', 'email', 'surname')


class EditReservationForm(ReservationForm):
    class Meta:
        model = Reservation
        fields = ('sports_ground', 'start_time', 'end_time', 'is_accepted')


class ManageReservationsForm(forms.Form):
    action = forms.ChoiceField(
        choices=Reservation.ACTION_CHOICES,
        widget=forms.Select()
    )
    def __init__(self, place, *args, **kwargs):
        super(ManageReservationsForm, self).__init__(*args, **kwargs)
        reservations = Reservation.objects.filter(
            sports_ground__place=place,
            is_accepted=False
        )
        self.fields['reservations'] = forms.ModelMultipleChoiceField(
            queryset=reservations,
            widget=forms.CheckboxSelectMultiple()
        )

class EditPlaceForm(forms.ModelForm):
    class Meta:
        model = Place
        exclude = ('name', 'administrator')

boiska/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView
from django.views import View
from django.http import Http404
from django.urls import reverse

import datetime
from calendar import Calendar

from .models import Place, Reservation
from .forms import (NewReservationForm, ManageReservationsForm,
    EditReservationForm, EditPlaceForm)


class IndexView(ListView):
    """
    Main page of the site. List of all locations.
    """
    model = Place
    template_name = 'boiska/index.html'


class PlaceView(View):
    """
    Description of a place.
    Calendar showing availability of sports grounds.
    """

    EMPTY = 0
    BUSY = 1
    VERY_BUSY = 2

    template_name = 'boiska/place.html'

    def get(self, request, place_name, year=None, month=None):
        self.place = get_object_or_404(Place, name=place_name)
        self.place_name = place_name
        self.year = year
        self.month = month
        self.prepare_and_check_year_month()
        self.prepare_next_and_previous_month_urls()
        my_calendar = self.availability_calendar()
        context = {
            'place': self.place,
            'calendar': my_calendar,
            'year': self.year,
            'month': self.month,
            'previous_month_url': self.previous_month_url,
            'next_month_url': self.next_month_url,
        }
        return render(request, self.template_name, context)

    def prepare_and_check_year_month(self):
        now = datetime.datetime.now()
        if self.year == None:
            self.year = now.year
        else:
            self.year = int(self.year)
        if self.month == None:
            self.month = now.month
        else:
            self.month = int(self.month)
        if self.month < 1 or self.month > 12:
            raise Http404

    def prepare_next_and_previous_month_urls(self):
        previous_month = {
            'year': self.year,
            'month': self.month - 1
        }
        next_month = {
            'year': self.year,
            'month': self.month + 1
        }
        if previous_month['month'] == 0:
            previous_month['month'] = 12
            previous_month['year'] = self.year - 1
        if next_month['month'] == 13:
            next_month['month'] = 1
            next_month['year'] = self.year + 1
        self.previous_month_url = reverse(
            'boiska:place',
            args=[self.place_name, previous_month['year'], previous_month['month']]
        )
        self.next_month_url = reverse(
            'boiska:place',
            args=[self.place_name, next_month['year'], next_month['month']]
        )

    def availability_calendar(self):
        """
        Availability calendar returns a list of week lists.
        """
        my_calendar = []
        for day in Calendar().itermonthdays2(self.year, self.month):
            day_dict = {
                'month_day': day[0],
                'week_day': day[1],
                'availability': None,
            }
            if day_dict['week_day'] == 0:
                my_calendar.append([])
            if day_dict['month_day'] != 0:
                day_dict['availability'] = self.check_availability(day_dict['month_day'])
            my_calendar[-1].append(day_dict)
        return my_calendar

    def check_availability(self, month_day):
        """
        Check availability of place's sports grounds on a particuar day.
        """
        event_date = datetime.date(self.year, self.month, month_day)
        time_sum = datetime.timedelta()
        total = datetime.timedelta()
        today = datetime.date.today()

        for sports_ground in self.place.sports_grounds.all():
            reservations = sports_ground.reservations.filter(
                event_date=event_date,
                is_accepted=True
            )
            for reservation in reservations:
                start_time = datetime.datetime.combine(today, reservation.start_time)
                end_time = datetime.datetime.combine(today, reservation.end_time)
                time_sum += end_time - start_time
            opening_time = datetime.datetime.combine(today, sports_ground.opening_time)
            closing_time = datetime.datetime.combine(today, sports_ground.closing_time)
            total += closing_time - opening_time

        if total == datetime.timedelta():
            return self.EMPTY
        result = time_sum / total
        if result > 0.6:
            return self.VERY_BUSY
        elif result > 0.3:
            return self.BUSY
        else:
            return self.EMPTY


class PlaceDayView(View):
    """
    Show reservations of sports grounds on a particular day.
    User can do a reservation using ReservationForm. Date and sports_ground
    fields are added automatically to the form after validation.
    """

    template_name = 'boiska/place_day.html'

    def get(self, request, place_name, year, month, day):
        self.initial_settings(place_name, year, month, day)
        self.prepare_context()
        if not self.is_date_valid():
            raise Http404
        new_reservation_form = NewReservationForm(self.place)
        self.context['new_reservation_form'] = new_reservation_form
        return render(request, self.template_name, self.context)

    def post(self, request, place_name, year, month, day):
        self.initial_settings(place_name, year, month, day)
        self.prepare_context()
        if not self.is_date_valid():
            raise Http404
        self.context['result_message'] = None
        new_reservation_form = NewReservationForm(data=request.POST)
        if new_reservation_form.is_valid():
            reservation = new_reservation_form.save(commit=False)
            reservation.event_date = datetime.date(self.year, self.month, self.day)
            reservation.save()
            self.context['result_message'] = 'Twoja rezerwacja czeka na akceptację.'
        else:
            self.context['result_message'] = 'Twoja rezerwacja zawiera błędy.'
        self.context['new_reservation_form'] = new_reservation_form
        return render(request, self.template_name, self.context)

    def initial_settings(self, place_name, year, month, day):
        self.place_name = place_name
        self.year = int(year)
        self.month = int(month)
        self.day = int(day)
        self.place = get_object_or_404(Place, name=self.place_name)
        self.sports_grounds = self.place.sports_grounds.all()

    def prepare_context(self):
        self.context = {
            'place_name': self.place_name,
            'date': str(self.year) + '/' + str(self.month) + '/' + str(self.day),
            'sports_grounds': self.sports_grounds,
            'new_reservation_form': None,
            'result_message': None,
        }

    def is_date_valid(self):
        try:
            datetime.date(self.year, self.month, self.day)
            return True
        except:
            return False


class PlaceAdminView(View):
    """
    Administrative panel for a Place administrator.
    """

    template_name = 'boiska/place_admin.html'

    def get(self, request, place_name):
        self.initial_settings(place_name)
        self.prepare_context()
        self.prepare_reservations_not_accepted()
        manage_reservations_form = ManageReservationsForm(self.place)
        self.context['manage_reservations_form'] = manage_reservations_form
        return render(request, self.template_name, self.context)

    def post(self, request, place_name):
        self.initial_settings(place_name)
        self.prepare_context()
        self.prepare_reservations_not_accepted()
        manage_reservations_form = ManageReservationsForm(
            self.place,
            data=request.POST
        )
        if manage_reservations_form.is_valid():
            reservations_ids = request.POST.getlist('reservations')
            reservations = Reservation.objects.filter(
                sports_ground__in=self.sports_grounds,
                id__in=reservations_ids
            )
            action = int(request.POST['action'])
            self.apply_action_to_selected_reservations(reservations, action)
        return render(request, self.template_name, self.context)

    def initial_settings(self, place_name):
        self.place = get_object_or_404(Place, name=place_name)
        self.sports_grounds = self.place.sports_grounds.all()

    def prepare_context(self):
        self.context = {
            'place': self.place,
            'sports_grounds': self.sports_grounds,
            'reservations_not_accepted': None,
            'manage_reservations_form': None,
            'result_messages': None,
        }

    def prepare_reservations_not_accepted(self):
        reservations_not_accepted = []
        for sports_ground in self.sports_grounds:
            for reservation in sports_ground.reservations.filter(is_accepted=False):
                reservations_not_accepted.append(reservation)
        self.context['reservations_not_accepted'] = reservations_not_accepted

    def apply_action_to_selected_reservations(self, reservations, action):
        result_messages = []
        for reservation in reservations:
            if action == Reservation.ACCEPT:
                overlap = self.reservation_overlap(reservation)
                if overlap == False:
                    reservation.is_accepted = True
                    reservation.save()
                    result_messages.append(
                        'Zaakceptowano: ' + str(reservation)
                    )
                else:
                    result_messages.append(
                        'Rezerwacja nachodzi na inną: ' + str(reservation)
                    )
            elif action == Reservation.DELETE:
                reservation.delete()
                result_messages.append('Usunięto: ' + str(reservation))
        self.context['result_messages'] = result_messages

boiska/templates/boiska/base.html
{% load staticfiles %}
<!DOCTYPE HTML>
<html lang="pl-PL">
    <head>
        <title>Rezerwacja boisk</title>
        <meta charset="UTF-8">
        <meta name="author" content="Piotr Miara">
        <meta content="text/html; charset=utf-8" http-equiv="Content-Type">
        <link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}">
        <link type="text/css" rel="stylesheet" href="{% static 'css/jquery.timepicker.css' %}">
        <script type="text/javascript" src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/jquery.timepicker.min.js' %}"></script>
    </head>
    <body>
        <header>
            <h1 id="logo">
                <a href="{% url 'boiska:index' %}">
                    Rezerwacja boisk
                </a>
            </h1>
        </header>
        <div id="main_container">
            {% block content %}
            {% endblock content %}
        </div>
        <footer>
        </footer>
    </body>
</html>

boiska/templates/boiska/edit_place.html
{% extends 'boiska/base.html' %}
{% block content %}
    <h3><a href="{% url 'boiska:place_admin' place_name %}">
        {{ place_name }}</a>
        - edycja
    </h3>
    <form method="POST">
        {% csrf_token %}
        {{ edit_place_form.as_p }}
        <button type="submit">Zapisz</button>
    </form>
{% endblock content %}

boiska/templates/boiska/edit_reservation.html
{% extends 'boiska/base.html' %}
{% block content %}
    <h3><a href="{% url 'boiska:place_admin' place_name %}">
        {{ place_name }}</a>
        - edycja rezerwacji
    </h3>
    <h4>{{ reservation }}</h4>
    <form method="POST">
        {% csrf_token %}
        {{ edit_reservation_form.as_p }}
        <button type="submit">Zapisz</button>
    </form>
    <script>
        $(function() {
            $('#id_start_time, #id_end_time').timepicker({
                'timeFormat': 'H:i',
                'disableTextInput': true,
                'scrollDefault': 'now',
            });
        });
    </script>
{% endblock content %}

boiska/templates/boiska/index.html
{% extends 'boiska/base.html' %}
{% load staticfiles %}
{% block content %}
    <p>Strona główna</p>
    <ul id="places">
        {% for place in place_list %}
        <li>
            <h3>
                <a href="{% url 'boiska:place' place.name %}">
                    {{ place.name }}
                </a>
            </h3>
        </li>
        {% endfor %}
    </ul>
{% endblock content %}

boiska/templates/boiska/place.html
{% extends 'boiska/base.html' %}
{% load custom_tags %}
{% block content %}
    <h3>{{ place.name }}</h3>
    <p>{{ place.description }}</p>
    <br />
    <h4>Dane kontaktowe:</h4>
    <ul>
        <li>{{ place.street }}, {{ place.city }}</li>
        <li>{{ place.phone_number }}</li>
    </ul>
    <h4>Dostępność boisk</h4>
    <table>
        <tr>
            <td>
                <a href="{{ previous_month_url }}">&lt;</a>
            </td>
            <th colspan="5">
                {{ month|polish_month_name }}
            </th>
            <td>
                <a href="{{ next_month_url }}">&gt;</a>
            </td>
        </tr>
        {% for week in calendar %}
        <tr>
            {% for day in week %}
            {% if day.month_day %}
            <td class="day_color_{{ day.availability }}">
                <a href="{% url 'boiska:place_day' place.name year month day.month_day %}">
                    {{ day.month_day }}
                </a>
            </td>
            {% else %}
            <td class="blank_day"></td>
            {% endif %}
            {% endfor %}
        </tr>
        {% endfor %}
    </table>
{% endblock content %}

boiska/templates/boiska/place_admin.html
{% extends 'boiska/base.html' %}
{% block content %}
    <h2>{{ place.name }}</h2>
    <p>{{ place.description }}</p>
    <h4>Dane kontaktowe:</h4>
    <ul>
        <li>{{ place.street }}, {{ place.city }}</li>
        <li>{{ place.phone_number }}</li>
    </ul>
    <a href="{% url 'boiska:edit_place' place.name %}">Edytuj dane</a>
    {% for sports_ground in sports_grounds %}
        <h4>{{ sports_ground }}</h4>
    {% endfor %}
    <h3>Rezerwacje do zaakceptowania</h3>
    {% for message in result_messages %}
    <p>{{ message }}</p>
    {% endfor %}
    <form method="POST">
        {% csrf_token %}
        <button type="submit">Go</button>
        {{ manage_reservations_form.action }}
        <ul>
        {% for reservation in manage_reservations_form.reservations %}
            <li>
            {{ reservation }} 
            <a href="{% url 'boiska:edit_reservation' place.name reservation.choice_value %}">
                Edytuj
            </a>
            </li>
        {% endfor %}
        </ul>
    </form>
{% endblock content %}

boiska/templates/boiska/place_day.html
{% extends 'boiska/base.html' %}
{% load staticfiles %}
{% load custom_tags %}
{% block content %}
    <a href="{% url 'boiska:place' place_name %}">
        <h3>{{ place_name }}</h3>
    </a>
    <br />
    <p id="result_message">
      {{ result_message }}
    </p>
    <h4>Dostępność boisk w dniu {{ date }}</h4>
    {% for sports_ground in sports_grounds %}
    <div>
        <h5>{{ sports_ground.local_name }}</h5>
        <p>
            {{ sports_ground.opening_time|time:"H:i" }} -
            {{ sports_ground.closing_time|time:"H:i" }}
        </p>
        {% with reservations=sports_ground.reservations|filter_day:date %}
        {% for reservation in reservations|sort_by:'start_time' %}
            {% if reservation.is_accepted %}
        <div class="reserved">
            {{ reservation.surname }}, {{ reservation.email }},
            {{ reservation.start_time|time:'H:i' }} -
            {{ reservation.end_time|time:'H:i' }}
        </div>
            {% endif %}
        {% endfor %}
        {% endwith %}
    </div>
    {% endfor %}
    <h4>Zarezerwuj boisko</h4>
    <form method="POST" id="reservation_form">
    {% csrf_token %}
        {{ new_reservation_form.as_p }}
        <button type="submit">Zarezerwuj</button>
    </form>
    <script>
        $(function() {
            $('#id_start_time, #id_end_time').timepicker({
                'timeFormat': 'H:i',
                'disableTextInput': true,
                'scrollDefault': 'now',
            });
        });
    </script>
{% endblock content %}